version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      NATS_SERVER: nats://nats:4222
    ports: 
      - '3000:3000'
  
  storage:
    build: 
      context: .
      dockerfile: ./packages/storage/Dockerfile
    environment:
      DB_HOST: postgres
      NATS_SERVER: nats://nats:4222
    depends_on:
      - nats
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  nats:
    container_name: nats
    image: nats:2.9-alpine
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'
