version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: ./packages/api/Dockerfile
  
  storage:
    build: 
      context: .
      dockerfile: ./packages/storage/Dockerfile
    depends_on:
      - nats
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
  
  nats:
    container_name: nats
    image: nats:2.9-alpine
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'
    