version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
    - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  nats:
    container_name: nats
    image: nats
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'
